name: basic GHA pipeline

on:
  push: 
    branches: ["master"]

jobs:
  Example-Actions-Job:
    name: Exploring GitHub Actions
    runs-on: self-hosted
    steps:
      - name: print a statement
        run: echo "basic GHA pipeline run successfull"
