name: node-app-CI pipeline
on: [push]

jobs:
  build:
    runs-on: Lix-ubuntu
    
    steps:
    - name: checkout code
      uses: actions/checkout@v7
    - name: setup node
      uses: actions/setup-node@v7
      with:
        node-version: 24 
    - name: install packages
      run: npm install
    - name: Run application
      run: 
        node npm start & 
        sleep 5
        curl http://localhost:3000
      
