name: CI pipeline
on: [push]

jobs:
  build:
    runs-on: Lix-ubuntu
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: setup node
        uses: actions/checkout@v4
        with:
          node version: 24 
      - name: install packages
        run: npm install
      - name: run applicaton
        run:
          node server.js &
          sleep 5s
          curl "http://localhost:3000"
          pkill -f "server.js"
